import { Inter } from "next/font/google";
import "./globals.css";
import "./font.css"
import { SpinProvider } from '@/contexts/spinContext';
import { GlobalProvider } from "@/contexts/globalContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider>
        <SpinProvider>
          <body className={inter.className}>{children}</body>
        </SpinProvider>
      </GlobalProvider>
    </html>
  );
}
